package br.com.siecola.aws_batch_job_processor.model;

import br.com.siecola.aws_batch_job_processor.enums.JobStatus;
import br.com.siecola.aws_batch_job_processor.enums.JobType;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "job")
public class Job {

    public static final String ID = "id";
    public static final String USERNAME = "username";
    public static final String STATUS = "status";
    public static final String TYPE = "type";
    public static final String NUM_REGISTERS = "numberOfRegisters";
    public static final String QUEUE = "queue";
    public static final String DEFINITION = "definition";
    public static final String VCPU = "vCpu";
    public static final String MEMORY = "memory";
    public static final String ATTEMPTS = "attempts";
    public static final String TTL = "ttl";


    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = ID)
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = USERNAME)
    private String username;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = STATUS)
    private JobStatus status;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = TYPE)
    private JobType type;

    @DynamoDBAttribute(attributeName = NUM_REGISTERS)
    private int numberOfRegisters;

    @DynamoDBAttribute(attributeName = QUEUE)
    private String queue;

    @DynamoDBAttribute(attributeName = DEFINITION)
    private String definition;

    @DynamoDBAttribute(attributeName = VCPU)
    private int vCpu;

    @DynamoDBAttribute(attributeName = MEMORY)
    private int memory;

    @DynamoDBAttribute(attributeName = ATTEMPTS)
    private int attempts;

    @DynamoDBAttribute(attributeName = TTL)
    private long ttl;

    public String getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setId(String id) {
        this.id = id;
    }

    public JobStatus getStatus() {
        return status;
    }

    public void setStatus(JobStatus status) {
        this.status = status;
    }

    public JobType getType() {
        return type;
    }

    public void setType(JobType type) {
        this.type = type;
    }

    public int getNumberOfRegisters() {
        return numberOfRegisters;
    }

    public void setNumberOfRegisters(int numberOfRegisters) {
        this.numberOfRegisters = numberOfRegisters;
    }

    public String getQueue() {
        return queue;
    }

    public void setQueue(String queue) {
        this.queue = queue;
    }

    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public int getvCpu() {
        return vCpu;
    }

    public void setvCpu(int vCpu) {
        this.vCpu = vCpu;
    }

    public int getMemory() {
        return memory;
    }

    public void setMemory(int memory) {
        this.memory = memory;
    }

    public int getAttempts() {
        return attempts;
    }

    public void setAttempts(int attempts) {
        this.attempts = attempts;
    }

    public long getTtl() {
        return ttl;
    }

    public void setTtl(long ttl) {
        this.ttl = ttl;
    }
}